### ISSUE TITLE
Loss and accuracy are NaN

### ISSUE THREAD

**Issue by danielvarab** [erickrf/multiffn-nli#4]
When I clone and run the implementation I get loss and accuracy as NaNs. My configuration runs on a GPU. Any insights?
![image](https://cloud.githubusercontent.com/assets/1228353/23366194/2ff33354-fd06-11e6-94d5-2d18535babc8.png)

**Comment by erickrf** [comment]
Are you using the latest version? There was a problem with the default value for the -c argument which was fixed. This could also happen if you given a very low value for -c.

**Comment by danielvarab** [comment]
This was the solution. Apperently the repo on my server was outdated. my apologies
