### ISSUE TITLE
shuffle_data

### ISSUE THREAD

**Issue by naoya-i** [erickrf/multiffn-nli#6]
Hello,

Thanks for creating a nice framework!

I found that the training data is not shuffled during training. I think that 

at https://github.com/erickrf/multiffn-nli/blob/master/src/utils.py#L55,

```
        shuffle_arrays([self.sentences1, self.sentences2,
                        self.sizes1, self.sizes2, self.labels])
```

should be

```
        shuffle_arrays(self.sentences1, self.sentences2,
                        self.sizes1, self.sizes2, self.labels)
```

Thanks!

**Comment by erickrf** [comment]
You are right! I never payed much attention to it since the shuffling has a marginal effect on performance. It's fixed now, thanks for pointing out.
