### ISSUE TITLE
Error: too few arguments 

### ISSUE THREAD

**Issue by ghost** [erickrf/multiffn-nli#7]
I tried to run your code and have a try by `python src/train.py --train=train_all.tsv --validation=dev_all.tsv --save=saved_models/ --model=mlp --embeddings=word_embed.txt --vocab=vocab.txt` but this error occurs: `train.py: error: too few arguments. ` But I think other params already have default values. Do you have any idea about it? Thx.

**Comment by erickrf** [comment]
You're missing the embeddings argument. It should be a numpy file with rows corresponding to your vocabulary or a raw text file with one word and its embedding values.

**Comment by ghost** [comment]
`embeddings` is not the correct argument?

**Comment by ghost** [comment]
OMG... `--` should be removed
