### ISSUE TITLE
Tensorflow 1.1 Compatibility

### ISSUE THREAD

**Issue by guytenn** [erickrf/multiffn-nli#9]
Hi,

The current version uploaded is not compatible with Tensorflow version 1.1, but it is easy to make it compatible. To do this two changes need to be made in decomposable.py:
1. Change dropout placeholder size parameter from None to [].
2. Add the following lines after the definition of embedded1 and embedded2 in __init__:
embedded1 = tf.cast(embedded1, "float")
embedded2 = tf.cast(embedded2, "float")

This makes everything able to run on tensorflow 1.1

**Comment by erickrf** [comment]
Hi, thanks for your input, but I checked that the current version runs fine with tensorflow 1.1. I did change the dropout placeholder for style conformity, but I don't think the float cast has any effect.
